version: '3'

services:
  phoenix:
    build:
      context: ./api
    environment:
      PGUSER: postgres
      PGPASSWORD: 0504
      PGDATABASE: apiproject_dev
      PGPORT: 5432
      PGHOST: localhost
    ports:
      - 4000:4000
    depends_on:
      - db
  db:
    # We use the predefined Postgres image
    image: postgres:9.6
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
