version: "3.8"
services:
  back:
    container_name: apiproject_back
    image: apiproject/back
    build:
      context: ./api
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
      PGHOST: ${PGHOST}
    ports:
      - "4000:4000"
    depends_on:
      - db
  front:
    container_name: apiprojet_front
    image: apiproject/front
    build:
      context: ./client
    ports:
      - "8080:8080"
    depends_on:
      - back
    restart: always
  db:
    container_name: apiproject_db
    image: postgres:12.8
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "dbdata:/var/lib/postgresql/data"
    restart: always
volumes:
  dbdata:
